// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlzgunaejqdpddlukcxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhsemd1bmFlanFkcGRkbHVrY3hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3ODUxNjEsImV4cCI6MjA2ODM2MTE2MX0.a_deSHRFO68YvJfPz0SN9IAoJlprMZWZ53BcAJ_lhhU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});